const Cars = [
    {
        id: 1,
        name: "Test Aracı",
        fuel: "Gasoline",
        year: "2019",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/ghost.png",
        price: "410",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "blue"
    },
    {
        id: 2,
        name: "Mercedes Maybach",
        fuel: "Gasoline",
        year: "2024",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/maybach.png",
        price: "390",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "black"
    },
    {
        id: 3,
        name: "Lamborghini Huracan",
        fuel: "Gasoline",
        year: "2021",
        gear: "Automatic",
        type: "Coupe",
        image: "/car_png/lamborghini.png",
        price: "380",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "blue"
    },
    {
        id: 4,
        name: "Porsche Carrera",
        fuel: "Gasoline",
        year: "2019",
        gear: "Automatic",
        type: "Hatchback",
        image: "/car_png/porsche.png",
        price: "365",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "orange"
    },
    {
        id: 5,
        name: "Rolce Royce Cullinan",
        fuel: "Diesel",
        year: "2024",
        gear: "Automatic",
        type: "SUV",
        image: "/car_png/cullinan.png",
        price: "350",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "black"
    },
    {
        id: 6,
        name: "Land Rover Range Rover",
        fuel: "Diesel",
        year: "2024",
        gear: "Automatic",
        type: "SUV",
        image: "/car_png/landrover.png",
        price: "350",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 7,
        name: "Porsche Taycan",
        fuel: "Electric",
        year: "2020",
        gear: "Automatic",
        type: "Hatchback",
        image: "/car_png/taycan.png",
        price: "190",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "blue"
    },
    {
        id: 8,
        name: "Mercedes S400",
        fuel: "Gasoline",
        year: "2023",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/sClasse.png",
        price: "335",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "black"
    },
    {
        id: 9,
        name: "Aston Martin DB12",
        fuel: "Gasoline",
        year: "2023",
        gear: "Manual",
        type: "Coupe",
        image: "/car_png/db12.png",
        price: "320",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "blue"
    },
    {
        id: 10,
        name: "Lexus LX-570",
        fuel: "Gasoline",
        year: "2021",
        gear: "Automatic",
        type: "SUV",
        image: "/car_png/lx570.png",
        price: "315",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 11,
        name: "Bentley Continental GT",
        fuel: "Gasoline",
        year: "2023",
        gear: "Automatic",
        type: "Cabrio",
        image: "/car_png/continental.png",
        price: "285",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 12,
        name: "Maserati Granturismo",
        fuel: "Gasoline",
        year: "2022",
        gear: "Automatic",
        type: "Coupe",
        image: "/car_png/granturismo.png",
        price: "285",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 13,
        name: "Auid Q8",
        fuel: "Diesel",
        year: "2023",
        gear: "Automatic",
        type: "SUV",
        image: "/car_png/q8.png",
        price: "285",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "yellow"
    },
    {
        id: 14,
        name: "BMW X7",
        fuel: "Diesel",
        year: "2024",
        gear: "Automatic",
        type: "SUV",
        image: "/car_png/x7.png",
        price: "285",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 15,
        name: "Ford Mustang",
        fuel: "Diesel",
        year: "2018",
        gear: "Manual",
        type: "Coupe",
        image: "/car_png/mustang.png",
        price: "240",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "orange"
    },
    {
        id: 16,
        name: "Volvo XC90",
        fuel: "Diesel",
        year: "2023",
        gear: "Automatic",
        type: "SUV",
        image: "/car_png/xc90.png",
        price: "240",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 17,
        name: "Aston Martin DB11",
        fuel: "Gasoline",
        year: "2023",
        gear: "Automatic",
        type: "Coupe",
        image: "/car_png/astonmartin.png",
        price: "235",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "black"
    },  
    {
        id: 18,
        name: "Tesla Model S",
        fuel: "Electric",
        year: "2022",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/model_s.png",
        price: "220",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "black"
    },
    {
        id: 19,
        name: "BMW 520",
        fuel: "Diesel",
        year: "2021",
        gear: "Manual",
        type: "Sedan",
        image: "/car_png/520.png",
        price: "190",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 20,
        name: "McLaren P1",
        fuel: "Gasoline",
        year: "2013",
        gear: "Manual",
        type: "Coupe",
        image: "/car_png/mcLaren.png",
        price: "350",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "yellow"
    },
    {
        id: 21,
        name: "BMW 420",
        fuel: "Gasoline",
        year: "2022",
        gear: "Automatic",
        type: "Coupe",
        image: "/car_png/420.png",
        price: "175",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "gray"
    },
    {
        id: 22,
        name: "Volvo S90",
        fuel: "Gasoline",
        year: "2021",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/s90.png",
        price: "175",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 23,
        name: "Mercedes CLS",
        fuel: "Gasoline",
        year: "2022",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/cls.png",
        price: "170",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 24,
        name: "Mercedes X350",
        fuel: "Diesel",
        year: "2018",
        gear: "Automatic",
        type: "Pick-Up",
        image: "/car_png/xClasse.png",
        price: "170",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "white"
    },
    {
        id: 25,
        name: "Alfa Romeo Guilietta",
        fuel: "Diesel",
        year: "2019",
        gear: "Automatic",
        type: "Coupe",
        image: "/car_png/guilietta.png",
        price: "160",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "red"
    },
    {
        id: 26,
        name: "TOGG T10X",
        fuel: "Electric",
        year: "2023",
        gear: "Automatic",
        type: "SUV",
        image: "/car_png/togg.png",
        price: "160",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "red"
    },
    {
        id: 27,
        name: "Audi A6",
        fuel: "Diesel",
        year: "2019",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/a6.png",
        price: "145",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "gray"
    },
    {
        id: 28,
        name: "Chevrolet Camaro",
        fuel: "Gasoline",
        year: "2020",
        gear: "Automatic",
        type: "Cabrio",
        image: "/car_png/camaro.png",
        price: "145",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "gray"
    },
    {
        id: 29,
        name: "Volkswagen Arteon",
        fuel: "Gasoline",
        year: "2017",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/arteon.png",
        price: "135",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "yellow"
    },
    {
        id: 30,
        name: "Audi A3",
        fuel: "Diesel",
        year: "2018",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/a3.png",
        price: "125",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "yellow"
    },
    {
        id: 31,
        name: "Chrysler 300C",
        fuel: "Diesel",
        year: "2017",
        gear: "Automatic",
        type: "Sedan",
        image: "/car_png/chrysler.png",
        price: "105",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "blue"
    },
    {
        id: 32,
        name: "Ford F-150",
        fuel: "Diesel",
        year: "2018",
        gear: "Manual",
        type: "Pick-Up",
        image: "/car_png/f150.png",
        price: "105",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "blue"
    },
    {
        id: 33,
        name: "BMW i8",
        fuel: "Electric",
        year: "2017",
        gear: "Automatic",
        type: "Coupe",
        image: "/car_png/i8.png",
        price: "100",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "black"
    },
    {
        id: 34,
        name: "Volkswagen Amarok",
        fuel: "Diesel",
        year: "2019",
        gear: "Manual",
        type: "Pick-Up",
        image: "/car_png/amarok.png",
        price: "95",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "blue"
    },
    {
        id: 35,
        name: "Cupra Leon",
        fuel: "Gasoline",
        year: "2024",
        gear: "Automatic",
        type: "Hatchback",
        image: "/car_png/cupra.png",
        price: "95",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "gray"
    },
    {
        id: 36,
        name: "Volkswagen Caddy",
        fuel: "Diesel",
        year: "2018",
        gear: "Manual",
        type: "Van",
        image: "/car_png/caddy.png",
        price: "65",
        rentDate: "",
        returnDate: "",
        location: "",
        color: "gray"
    },
];

export default {
    Cars,
};